import json
import pickle
import shutil
import tempfile
from bisect import bisect_left
from pathlib import Path

import numpy as np
from joblib import Parallel, delayed
from tqdm import tqdm

import glow.effect
import glow.graph
from ._base import Analysis
from glow.experiment.exper import ExperimentScaled
from .mancova import get_llr, stat_dict_inv
from .prune import prune_greedy
from .cluster import cluster


_DEFAULT_MODEL = 'power_law'

_BEST_MODELS_PATH = Path(__file__).parent / 'best_models.json'


def _load_best_models():
    """Load best_models.json stored alongside analysis.py.

    Returns a dict mapping stat short-name -> best model name,
    or an empty dict if the file doesn't exist yet.
    """
    if _BEST_MODELS_PATH.exists():
        return json.loads(_BEST_MODELS_PATH.read_text())
    return {}


def get_best_model(get_stat):
    """Return the best size-adjustment model for a stat function.

    Looks up best_models.json (generated by stat_vs_size benchmark).
    Falls back to _DEFAULT_MODEL if no benchmark data is available.
    """
    import warnings
    best = _load_best_models()
    key = stat_dict_inv.get(get_stat)
    if key and key in best:
        return best[key]
    warnings.warn(
        f"No best_models.json found for stat '{key}'; defaulting to "
        f"'{_DEFAULT_MODEL}'. Run 'python -m glow.benchmark.stat_vs_size' "
        f"to generate data-driven model selection.",
        stacklevel=2,
    )
    return _DEFAULT_MODEL


class AnalysisGLOW(Analysis):
    """search a hierarchical segmentation for significant effects.

    Uses a disk-backed streaming pipeline: each permutation result is
    written to a temp directory, regression is accumulated online, and
    finalization reads the results in a single sweep.

    Attributes:
        children (np.array): (num_leaf - 1, 2) Ward children for observed data
        stat (np.array): (num_reg,) raw test statistics for observed
        size (np.array): (num_reg,) region sizes for observed
        pval (np.array): (num_reg,) FWER-controlled p-values
        effect_list (list): discovered Effect objects
    """

    def __init__(self, exp, n_perm_fwer,
                 n_perm_fwer_size_adjust=25,
                 alpha_fwer=.05, min_size=1, verbose=False,
                 n_jobs_perm=1, cloud_config=None, perm_dir=None,
                 size_adjust_model=None, **kwargs):
        """
        Args:
            exp: Experiment to analyze
            n_perm_fwer: Number of permutations for FWER control
            n_perm_fwer_size_adjust: Number of held-out permutations used
                exclusively to fit the size-adjustment regression (default 25).
                These are independent of the n_perm_fwer FWER permutations.
            alpha_fwer: Family-wise error rate
            min_size: Minimum region size
            verbose: Print progress
            n_jobs_perm: Number of parallel jobs for permutations
                (1=serial, -1=all cores)
            cloud_config: CloudConfig for AWS execution (if None, runs
                locally)
            perm_dir: path for permutation result files.  If provided,
                results are kept on disk for post-hoc inspection; if
                None a temp directory is created and cleaned up.
                Existing results in the directory are reused (resume).
            size_adjust_model: regression model for the size adjustment
                ('sqrt', 'power_law', etc.).  If None (default),
                auto-selected from stat_vs_size benchmark results
                (best_models.json).
        """
        super().__init__(exp, **kwargs)
        self.verbose = verbose

        if cloud_config is not None:
            self._run_on_cloud(exp, n_perm_fwer,
                              alpha_fwer, min_size, verbose,
                              cloud_config,
                              n_perm_fwer_size_adjust=n_perm_fwer_size_adjust,
                              size_adjust_model=size_adjust_model,
                              **kwargs)
            return

        b, num_img, num_vox = exp.y.shape
        model = size_adjust_model or get_best_model(self.get_stat)

        # Permutation index layout:
        #   0                                        = observed data
        #   1..n_perm_fwer                           = FWER null permutations
        #   n_perm_fwer+1..n_perm_fwer+n_perm_fwer_size_adjust = held-out fit permutations
        fit_start = n_perm_fwer + 1
        fit_end = n_perm_fwer + n_perm_fwer_size_adjust
        all_perm_indices = list(range(fit_end + 1))

        # set up directory for per-permutation result files
        _cleanup_dir = perm_dir is None
        if perm_dir is None:
            perm_dir = Path(tempfile.mkdtemp(prefix='glow_perm_'))
        else:
            perm_dir = Path(perm_dir)
            perm_dir.mkdir(parents=True, exist_ok=True)

        # scan for existing results (resume support)
        existing = set()
        XtX, Xty = None, None
        for f in sorted(perm_dir.glob('*_result.pkl')):
            try:
                perm_idx = int(f.name.split('_')[0])
            except ValueError:
                continue
            existing.add(perm_idx)
            if perm_idx >= fit_start:
                with open(f, 'rb') as fh:
                    r = pickle.load(fh)
                XtX, Xty = self.accumulate_regression(
                    r['size'], r['stat'], model, XtX, Xty)
                del r

        todo = [i for i in all_perm_indices if i not in existing]
        if existing and verbose:
            print(f'  resumed: {len(existing)} permutations found on disk, '
                  f'{len(todo)} remaining')

        if verbose:
            print(f'  [1/3] clustering {len(todo)} permutations '
                  f'({num_vox} voxels, {n_perm_fwer} FWER + {n_perm_fwer_size_adjust} fit) ...')

        if n_jobs_perm not in (0, 1) and todo:
            results = Parallel(
                n_jobs=n_jobs_perm,
                verbose=10 if verbose else 0,
            )(delayed(self._process_permutation)(exp, perm_idx)
              for perm_idx in todo)
            for r in results:
                p = r['perm_idx']
                with open(perm_dir / f'{p:06d}_result.pkl', 'wb') as fh:
                    pickle.dump(r, fh)
                if p >= fit_start:
                    XtX, Xty = self.accumulate_regression(
                        r['size'], r['stat'], model, XtX, Xty)
                del r
        else:
            for perm_idx in tqdm(todo, desc='permutations',
                                 disable=not verbose):
                r = self._process_permutation(exp, perm_idx)
                with open(perm_dir / f'{r["perm_idx"]:06d}_result.pkl',
                          'wb') as fh:
                    pickle.dump(r, fh)
                if perm_idx >= fit_start:
                    XtX, Xty = self.accumulate_regression(
                        r['size'], r['stat'], model, XtX, Xty)
                del r

        # fit regression from accumulated sufficient statistics
        if verbose:
            print(f'  [2/3] fitting size model ({model}) ...')
        mu_fn, _, beta = self.fit_size_regression_online(
            XtX, Xty, model, self.get_stat)
        self.adj_model = model
        self.adj_beta = beta

        # load observed (perm 0) — kept permanently
        with open(perm_dir / f'{0:06d}_result.pkl', 'rb') as fh:
            r0 = pickle.load(fh)
        stat_0 = np.asarray(r0['stat'], dtype=float)
        size_0 = np.asarray(r0['size'], dtype=float)
        children_0 = r0['children']
        del r0

        # pass 2: sweep temp files for adjusted max-stats
        if verbose:
            print(f'  [3/3] computing FWER p-values + pruning ...')
        reg_active = size_0 >= min_size
        stat_max_list = []
        for perm_idx in range(n_perm_fwer + 1):
            with open(perm_dir / f'{perm_idx:06d}_result.pkl', 'rb') as fh:
                r = pickle.load(fh)
            adj = (np.asarray(r['stat'], dtype=float)
                   - mu_fn(np.asarray(r['size'], dtype=float)))
            adj = np.nan_to_num(adj, nan=0.0, posinf=0.0, neginf=-30.0)
            stat_max_list.append(
                float(np.nanmax(adj[reg_active])) if reg_active.any()
                else float('-inf'))
            del r, adj
        stat_max_sorted = np.sort(stat_max_list)

        self._finalize_analysis(
            exp, n_perm_fwer, stat_0, size_0, children_0,
            mu_fn, stat_max_sorted,
            alpha_fwer, min_size)

        if _cleanup_dir:
            shutil.rmtree(perm_dir, ignore_errors=True)

    @classmethod
    def from_precomputed(cls, *, exp, get_stat, adj_model=None, adj_beta=None, verbose=False):
        """Construct a shell for finalization without running full __init__.

        The caller should then invoke _finalize_analysis() to compute p-values.
        """
        obj = cls.__new__(cls)
        obj.exp = exp if isinstance(exp, ExperimentScaled) else ExperimentScaled.from_exp(exp)
        obj.get_stat = get_stat
        obj.adj_model = adj_model
        obj.adj_beta = adj_beta
        obj.verbose = verbose
        return obj

    def _process_permutation(self, exp, perm_idx):
        """Run one permutation: cluster, compute stats and sizes."""
        _exp = exp.permute(perm_idx)
        children = cluster(exp=_exp)

        stat_row = self.get_stat_perm(exp=_exp, children=children)
        stat = stat_row.ravel()
        num_vox = _exp.y.shape[2]
        size = glow.graph.node_sum(np.ones(num_vox, dtype=int), children)

        del _exp
        return {
            'perm_idx': perm_idx,
            'children': children,
            'stat': stat,
            'size': size,
        }

    @classmethod
    def rerun_permutation(cls, exp, perm_idx, get_stat=get_llr):
        """Re-run a single permutation for inspection.

        Since permutations are deterministic given ``perm_idx``, this
        faithfully reproduces the result without needing stored data.

        Returns:
            dict with keys ``perm_idx``, ``children``, ``stat``, ``size``
        """
        ana = cls.from_precomputed(exp=exp, get_stat=get_stat)
        return ana._process_permutation(exp, perm_idx)

    # models that fit in log(stat) space and need exp() to predict
    _LOG_STAT_MODELS = {'power_law', 'log_linear'}
    # models that require stat > 0 (because they take log(stat))
    _POSITIVE_STAT_MODELS = {'power_law', 'log_linear'}

    @staticmethod
    def _x1_from_size(sz, model):
        """Compute the size feature for a given model."""
        if model == 'linear' or model == 'log_linear':
            return sz
        elif model == 'sqrt':
            return np.sqrt(sz)
        elif model in ('power_law', 'log_size'):
            return np.log(np.maximum(sz, 1))
        elif model == 'reciprocal':
            return 1.0 / np.maximum(sz, 1)
        else:
            raise ValueError(f'Unknown model: {model}')

    @classmethod
    def predict_null_mean(cls, size, model, beta):
        """Predict E[stat | H0] given region sizes, model name, and coeffs.

        Args:
            size: scalar or array of region sizes (voxels)
            model (str): 'linear', 'sqrt', 'power_law', 'log_size',
                'log_linear', or 'reciprocal'
            beta (np.array): regression coefficients

        Returns:
            predicted mean stat under H0
        """
        sz = np.asarray(size, dtype=float)
        x1 = cls._x1_from_size(sz, model)
        pred = beta[0] + beta[1] * x1
        if model in cls._LOG_STAT_MODELS:
            return np.exp(pred)
        return pred

    @classmethod
    def fit_size_regression_online(cls, XtX, Xty, model, get_stat=None):
        """Fit size regression from pre-accumulated sufficient statistics.

        Args:
            XtX: (2, 2) accumulated X^T X matrix
            Xty: (2,) accumulated X^T y vector
            model: any model name supported by predict_null_mean
            get_stat: stat function (stored on result for predict_null_mean)

        Returns:
            mu_fn: callable(size_array) -> predicted E[stat | H0]
            model: model name
            beta: regression coefficients
        """
        beta, _, _, _ = np.linalg.lstsq(XtX, Xty, rcond=None)
        def mu_fn(sz, _m=model, _b=beta):
            return cls.predict_null_mean(sz, _m, _b)
        return mu_fn, model, beta

    @classmethod
    def accumulate_regression(cls, size, stat, model, XtX=None, Xty=None):
        """Accumulate size-weighted (WLS) sufficient statistics.

        Each observation is weighted by its region size so that larger
        regions have proportionally more influence on the fit.
        Accumulates X'WX and X'Wy where W = diag(size).

        Args:
            size: (num_reg,) region sizes for this permutation
            stat: (num_reg,) stat values for this permutation
            model: any model name supported by _x1_from_size
            XtX: running (2, 2) matrix (None to initialize)
            Xty: running (2,) vector (None to initialize)

        Returns:
            XtX, Xty: updated sufficient statistics
        """
        s = np.asarray(size, dtype=float)
        y = np.asarray(stat, dtype=float)

        valid = np.isfinite(y) & (s > 0) & np.isfinite(s)
        if model in cls._POSITIVE_STAT_MODELS:
            valid &= (y > 0)

        s_v, y_v = s[valid], y[valid]
        x1 = cls._x1_from_size(s_v, model)
        yv = np.log(y_v) if model in cls._LOG_STAT_MODELS else y_v

        w = s_v
        x0 = np.ones(x1.shape[0])
        if XtX is None:
            XtX = np.zeros((2, 2))
            Xty = np.zeros(2)
        XtX[0, 0] += (w * x0) @ x0
        XtX[0, 1] += (w * x0) @ x1
        XtX[1, 0] += (w * x0) @ x1
        XtX[1, 1] += (w * x1) @ x1
        Xty[0] += (w * x0) @ yv
        Xty[1] += (w * x1) @ yv
        return XtX, Xty

    def _finalize_analysis(self, exp, n_perm_fwer,
                          stat_0, size_0, children_0,
                          mu_fn, stat_max_sorted,
                          alpha_fwer, min_size,
                          prune_stat=None,
                          ):
        """Finalize: compute p-values from max-stat distribution, prune.

        Args:
            prune_stat (np.array): optional override for the stat array
                used by greedy pruning.  When None (default), ``stat_0``
                is used.  Pass e.g. LLR values here when the test
                statistic differs from the desired pruning criterion.
        """
        verbose = getattr(self, 'verbose', False)
        num_reg = stat_0.shape[0]

        llr_adjusted_0 = stat_0 - mu_fn(size_0.astype(float))
        llr_adjusted_0 = np.nan_to_num(llr_adjusted_0, nan=0.0,
                                        posinf=0.0, neginf=-30.0)

        self.alpha_fwer = alpha_fwer
        self.size = size_0
        self.stat = stat_0
        self.llr_adjusted_0 = llr_adjusted_0
        self.children = children_0

        reg_active = size_0 >= min_size
        if not reg_active.any():
            pval = np.full(num_reg, fill_value=np.nan)
        else:
            pval = np.full(num_reg, fill_value=-1.0)
            for reg_idx, z in enumerate(llr_adjusted_0):
                if np.isnan(z):
                    pval[reg_idx] = np.nan
                    continue
                n_total = len(stat_max_sorted)
                pval[reg_idx] = max(
                    1 - bisect_left(stat_max_sorted, z) / n_total,
                    1 / n_total)
            pval[~reg_active] = np.nan
        self.pval = pval

        n_total = len(stat_max_sorted)
        if n_total > 0:
            crit_idx = min(int(np.ceil(n_total * (1 - alpha_fwer))),
                           n_total - 1)
            self.adj_crit = float(stat_max_sorted[crit_idx])
        else:
            self.adj_crit = None

        self.sig_reg_list = list(np.where(self.pval <= alpha_fwer)[0])
        if verbose:
            print(f'  {len(self.sig_reg_list)} significant regions '
                  f'(alpha_fwer={alpha_fwer})')
            print('  pruning (greedy LLR) ...')

        _prune = stat_0 if prune_stat is None else prune_stat
        stat_gain = np.nan_to_num(_prune.astype(float), nan=0.0,
                                  posinf=0.0, neginf=0.0)

        reg_out_list, self.prune_info = prune_greedy(
            sig_reg_list=self.sig_reg_list,
            children=children_0,
            stat=stat_gain)

        self.effect_list = list()
        for reg_idx in reg_out_list:
            label_map = glow.graph.get_label_map(
                reg_idx_list=[reg_idx],
                mask_idx=exp.mask_idx,
                children=children_0)
            pval_fwer = self.pval[reg_idx]
            eff = glow.effect.Effect.from_exp_mask(
                mask=label_map > -1, exp=exp,
                reg_idx=reg_idx, pval_fwer=pval_fwer)
            self.effect_list.append(eff)

        if verbose:
            n_disc = len(self.effect_list)
            n_pruned = len(self.sig_reg_list) - n_disc
            print(f'  done: {n_disc} discovered, {n_pruned} pruned')

    def _run_on_cloud(self, exp, n_perm_fwer,
                     alpha_fwer, min_size, verbose,
                     cloud_config, n_perm_fwer_size_adjust=25,
                     size_adjust_model=None, **kwargs):
        """Run full analysis on AWS Batch (permutations + synthesis).

        Submits N+1+n_perm_fwer_size_adjust permutation jobs, then a
        synthesis job that polls S3 for all results before running
        ``_finalize_analysis`` on the cloud.  The final pickled
        AnalysisGLOW is downloaded and its attributes are copied onto
        ``self``.
        """
        from glow.aws import AWSBatchRunner
        import uuid

        print('running analysis on AWS cloud...')

        experiment_id = f'glow_{uuid.uuid4().hex[:8]}'

        ana_kwargs = {
            'get_stat': self.get_stat,
            'n_perm_fwer_size_adjust': n_perm_fwer_size_adjust,
            'alpha_fwer': alpha_fwer,
            'min_size': min_size,
            'size_adjust_model': size_adjust_model,
        }
        ana_kwargs.update(kwargs)

        runner = AWSBatchRunner(cloud_config)

        print('uploading experiment data...')
        runner.upload_experiment(exp, ana_kwargs, experiment_id)

        print('submitting permutation jobs...')
        submission = runner.submit_jobs(
            experiment_id=experiment_id,
            n_perm=n_perm_fwer + n_perm_fwer_size_adjust,
            skip_completed=True,
        )

        if submission.get('cancelled'):
            raise RuntimeError('job submission cancelled')

        perm_job_ids = submission['job_ids']

        print('submitting synthesis job...')
        synth_job_id = runner.submit_synthesis_job(
            experiment_id, n_perm_fwer + n_perm_fwer_size_adjust)

        all_job_ids = perm_job_ids + [synth_job_id]

        if verbose:
            runner.monitor_jobs(all_job_ids)
        else:
            print(f'submitted {len(perm_job_ids)} perm jobs + 1 synthesis job')

        print('downloading final analysis...')
        remote_ana = runner.download_final_analysis(experiment_id)

        _COPY_ATTRS = [
            'children', 'stat', 'size', 'pval', 'llr_adjusted_0',
            'sig_reg_list', 'effect_list', 'alpha_fwer', 'adj_crit',
            'prune_info', 'adj_model', 'adj_beta',
        ]
        for attr in _COPY_ATTRS:
            if hasattr(remote_ana, attr):
                setattr(self, attr, getattr(remote_ana, attr))

        print(f'cloud analysis complete: found {len(self.effect_list)} effects')
